easy_admin:
    entities:
       # List the entity class name you want to manage

        Product:
            class: App\Entity\Product
            # form : correspond au formulaire de cr√©ation
            form:
                fields:
                    - name
                    - description
                    - price
                    - isPublished
                    - imageName
                    - category
                    - publisher
            # list : correspond au tableau affichant les entites
            list:
                fields: [name, isPublished, category, publisher]
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Tag:
            class: App\Entity\Tag
    # Personnaliser nom Admin
    site_name:          Gestion du Back-office

